# Generated by Django 5.0.3 on 2024-05-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnBeispiele',
        ),
        migrations.DeleteModel(
            name='EnBeispielkode',
        ),
        migrations.DeleteModel(
            name='EnC1',
        ),
        migrations.DeleteModel(
            name='EnC2',
        ),
        migrations.DeleteModel(
            name='EnKode',
        ),
        migrations.DeleteModel(
            name='EnQ1',
        ),
        migrations.DeleteModel(
            name='EnQ2',
        ),
        migrations.DeleteModel(
            name='EnSanierung',
        ),
        migrations.DeleteModel(
            name='EnStandardanmerkung',
        ),
        migrations.DeleteModel(
            name='EnVideobeispiele',
        ),
        migrations.DeleteModel(
            name='EnVideobeispielekode',
        ),
    ]
