# Generated by Django 5.0.3 on 2024-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_enbeispiele_delete_enbeispielkode_delete_enc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnKode',
            fields=[
                ('en_id', models.IntegerField(blank=True, db_column='EN_ID', primary_key=True, serialize=False)),
                ('en_kap', models.TextField(blank=True, db_column='EN_Kap', null=True)),
                ('en_child', models.IntegerField(blank=True, db_column='EN_Child', null=True)),
                ('en_hauptkode', models.TextField(blank=True, db_column='EN_HauptKode', null=True)),
                ('en_lang', models.TextField(blank=True, db_column='EN_Lang', null=True)),
                ('en_beschreibung', models.TextField(blank=True, db_column='EN_Beschreibung', null=True)),
                ('en_c1', models.TextField(blank=True, db_column='EN_C1', null=True)),
                ('en_c2', models.TextField(blank=True, db_column='EN_C2', null=True)),
                ('en_sa', models.TextField(blank=True, db_column='EN_SA', null=True)),
                ('en_q1', models.TextField(blank=True, db_column='EN_Q1', null=True)),
                ('en_q2', models.TextField(blank=True, db_column='EN_Q2', null=True)),
                ('en_l1', models.TextField(blank=True, db_column='EN_L1', null=True)),
                ('en_l2', models.TextField(blank=True, db_column='EN_L2', null=True)),
                ('en_q2abweichend', models.TextField(blank=True, db_column='EN_Q2abweichend', null=True)),
                ('en_hinweis', models.TextField(blank=True, db_column='EN_HINWEIS', null=True)),
                ('en_c1text', models.TextField(blank=True, db_column='EN_C1Text', null=True)),
                ('en_c2text', models.TextField(blank=True, db_column='EN_C2Text', null=True)),
                ('en_q1text', models.TextField(blank=True, db_column='EN_Q1Text', null=True)),
                ('en_q2text', models.TextField(blank=True, db_column='EN_Q2Text', null=True)),
                ('en_c1check', models.TextField(blank=True, db_column='EN_C1Check', null=True)),
                ('en_c2check', models.TextField(blank=True, db_column='EN_C2Check', null=True)),
                ('en_lagetext', models.TextField(blank=True, db_column='EN_Lagetext', null=True)),
                ('en_kat', models.TextField(blank=True, db_column='EN_Kat', null=True)),
                ('en_beispielanzahl', models.TextField(blank=True, db_column='EN_Beispielanzahl', null=True)),
                ('en_videoanzahl', models.TextField(blank=True, db_column='EN_Videoanzahl', null=True)),
                ('en_spezial', models.TextField(blank=True, db_column='EN_Spezial', null=True)),
                ('en_kombi', models.TextField(blank=True, db_column='EN_Kombi', null=True)),
            ],
            options={
                'db_table': 'EN_Kode',
                'managed': False,
            },
        ),
    ]
