# Generated by Django 5.0.6 on 2024-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_enkode"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnC1",
            fields=[
                (
                    "enc1_id",
                    models.TextField(
                        blank=True,
                        db_column="ENC1_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enc1_child",
                    models.TextField(blank=True, db_column="ENC1_Child", null=True),
                ),
                (
                    "enc1_kurz",
                    models.TextField(blank=True, db_column="ENC1_Kurz", null=True),
                ),
                (
                    "enc1_text",
                    models.TextField(blank=True, db_column="ENC1_Text", null=True),
                ),
                (
                    "enc1_lang",
                    models.TextField(blank=True, db_column="ENC1_Lang", null=True),
                ),
                (
                    "enc1_quantkurz",
                    models.TextField(blank=True, db_column="ENC1_Quantkurz", null=True),
                ),
                (
                    "enc1_quantlang",
                    models.TextField(blank=True, db_column="ENC1_Quantlang", null=True),
                ),
                (
                    "enc1_dim",
                    models.TextField(blank=True, db_column="ENC1_Dim", null=True),
                ),
                (
                    "enc1_c2aus",
                    models.TextField(blank=True, db_column="ENC1_C2aus", null=True),
                ),
                (
                    "enc1_c2nicht",
                    models.TextField(blank=True, db_column="ENC1_C2Nicht", null=True),
                ),
                (
                    "enc1_min",
                    models.TextField(blank=True, db_column="ENC1_min", null=True),
                ),
                (
                    "enc1_max",
                    models.TextField(blank=True, db_column="ENC1_max", null=True),
                ),
                (
                    "enc1_grenz",
                    models.TextField(blank=True, db_column="ENC1_grenz", null=True),
                ),
                (
                    "enc1_stan",
                    models.TextField(blank=True, db_column="ENC1_stan", null=True),
                ),
            ],
            options={
                "db_table": "EN_C1",
                "managed": False,
            },
        ),
    ]
