# Generated by Django 5.0.6 on 2024-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_enc1"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnBeispiele",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enb_id", models.TextField(blank=True, db_column="ENB_ID", null=True)),
                (
                    "enb_enid",
                    models.TextField(blank=True, db_column="ENB_ENID", null=True),
                ),
                (
                    "enb_bild",
                    models.TextField(blank=True, db_column="ENB_Bild", null=True),
                ),
                (
                    "enb_druck",
                    models.TextField(blank=True, db_column="ENB_druck", null=True),
                ),
                (
                    "enb_auskleidung",
                    models.TextField(
                        blank=True, db_column="ENB_Auskleidung", null=True
                    ),
                ),
                (
                    "enb_reparatur",
                    models.TextField(blank=True, db_column="ENB_Reparatur", null=True),
                ),
                (
                    "enb_punktuell",
                    models.TextField(blank=True, db_column="ENB_Punktuell", null=True),
                ),
                (
                    "enb_typ",
                    models.TextField(blank=True, db_column="ENB_Typ", null=True),
                ),
                (
                    "enb_raus",
                    models.TextField(blank=True, db_column="ENB_raus", null=True),
                ),
                (
                    "enb_pruefung",
                    models.TextField(blank=True, db_column="ENB_Pruefung", null=True),
                ),
                (
                    "enb_bemerkung",
                    models.TextField(blank=True, db_column="ENB_Bemerkung", null=True),
                ),
            ],
            options={
                "db_table": "EN_Beispiele",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnBeispielkode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enk_id", models.TextField(blank=True, db_column="ENK_ID", null=True)),
                (
                    "enk_enbid",
                    models.TextField(blank=True, db_column="ENK_ENBID", null=True),
                ),
                (
                    "enk_kode",
                    models.TextField(blank=True, db_column="ENK_Kode", null=True),
                ),
                ("enk_c1", models.TextField(blank=True, db_column="ENK_C1", null=True)),
                ("enk_c2", models.TextField(blank=True, db_column="ENK_C2", null=True)),
                ("enk_ca", models.TextField(blank=True, db_column="ENK_CA", null=True)),
                ("enk_q1", models.TextField(blank=True, db_column="ENK_Q1", null=True)),
                ("enk_q2", models.TextField(blank=True, db_column="ENK_Q2", null=True)),
                ("enk_v", models.TextField(blank=True, db_column="ENK_V", null=True)),
                (
                    "enk_pos1",
                    models.TextField(blank=True, db_column="ENK_Pos1", null=True),
                ),
                (
                    "enk_pos2",
                    models.TextField(blank=True, db_column="ENK_Pos2", null=True),
                ),
                (
                    "enk_bereich",
                    models.TextField(blank=True, db_column="ENK_Bereich", null=True),
                ),
                (
                    "enk_langtext",
                    models.TextField(blank=True, db_column="ENK_Langtext", null=True),
                ),
                (
                    "enk_anmerkung",
                    models.TextField(blank=True, db_column="ENK_Anmerkung", null=True),
                ),
                ("enk_ok", models.TextField(blank=True, db_column="ENK_Ok", null=True)),
            ],
            options={
                "db_table": "EN_BeispielKode",
                "managed": False,
            },
        ),
    ]
