# Generated by Django 5.0.6 on 2024-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_enbeispiele_enbeispielkode"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnC2",
            fields=[
                (
                    "enc2_id",
                    models.TextField(
                        blank=True,
                        db_column="ENC2_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enc2_child",
                    models.TextField(blank=True, db_column="ENC2_Child", null=True),
                ),
                (
                    "enc2_kurz",
                    models.TextField(blank=True, db_column="ENC2_Kurz", null=True),
                ),
                (
                    "enc2_text",
                    models.TextField(blank=True, db_column="ENC2_Text", null=True),
                ),
                (
                    "enc2_lang",
                    models.TextField(blank=True, db_column="ENC2_Lang", null=True),
                ),
                (
                    "enc2_stan",
                    models.TextField(blank=True, db_column="ENC2_Stan", null=True),
                ),
            ],
            options={
                "db_table": "EN_C2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnQ1",
            fields=[
                (
                    "enq1_id",
                    models.TextField(
                        blank=True,
                        db_column="ENQ1_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enq1_child",
                    models.TextField(blank=True, db_column="ENQ1_Child", null=True),
                ),
                (
                    "enq1_dim",
                    models.TextField(blank=True, db_column="ENQ1_Dim", null=True),
                ),
                (
                    "enq1_lang",
                    models.TextField(blank=True, db_column="ENQ1_Lang", null=True),
                ),
                (
                    "enq1_kurz",
                    models.TextField(blank=True, db_column="ENQ1_Kurz", null=True),
                ),
            ],
            options={
                "db_table": "EN_Q1",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnQ2",
            fields=[
                (
                    "enq2_id",
                    models.TextField(
                        blank=True,
                        db_column="ENQ2_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enq2_child",
                    models.TextField(blank=True, db_column="ENQ2_Child", null=True),
                ),
                (
                    "enq2_dim",
                    models.TextField(blank=True, db_column="ENQ2_DIM", null=True),
                ),
                (
                    "enq2_lang",
                    models.TextField(blank=True, db_column="ENQ2_Lang", null=True),
                ),
                (
                    "enq2_kurz",
                    models.TextField(blank=True, db_column="ENQ2_Kurz", null=True),
                ),
            ],
            options={
                "db_table": "EN_Q2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnVideobeispiele",
            fields=[
                (
                    "env_idalt",
                    models.TextField(blank=True, db_column="ENV_IDalt", null=True),
                ),
                (
                    "env_id",
                    models.TextField(
                        blank=True,
                        db_column="ENV_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "env_enobid",
                    models.TextField(blank=True, db_column="ENV_ENOBID", null=True),
                ),
                (
                    "env_video",
                    models.TextField(blank=True, db_column="ENV_Video", null=True),
                ),
                (
                    "env_bild",
                    models.TextField(blank=True, db_column="ENV_Bild", null=True),
                ),
                (
                    "env_typ",
                    models.TextField(blank=True, db_column="ENV_Typ", null=True),
                ),
                (
                    "env_druck",
                    models.TextField(blank=True, db_column="ENV_Druck", null=True),
                ),
            ],
            options={
                "db_table": "EN_Videobeispiele",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnVideobeispielekode",
            fields=[
                (
                    "envb_id",
                    models.TextField(
                        blank=True,
                        db_column="ENVB_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "envb_envid",
                    models.TextField(blank=True, db_column="ENVB_ENVID", null=True),
                ),
                (
                    "envb_kode",
                    models.TextField(blank=True, db_column="ENVB_Kode", null=True),
                ),
                (
                    "envb_c1",
                    models.TextField(blank=True, db_column="ENVB_C1", null=True),
                ),
                (
                    "envb_c2",
                    models.TextField(blank=True, db_column="ENVB_C2", null=True),
                ),
                (
                    "envb_ca",
                    models.TextField(blank=True, db_column="ENVB_CA", null=True),
                ),
                (
                    "envb_q1",
                    models.TextField(blank=True, db_column="ENVB_Q1", null=True),
                ),
                (
                    "envb_q2",
                    models.TextField(blank=True, db_column="ENVB_Q2", null=True),
                ),
                ("envb_v", models.TextField(blank=True, db_column="ENVB_V", null=True)),
                (
                    "envb_pos1",
                    models.TextField(blank=True, db_column="ENVB_Pos1", null=True),
                ),
                (
                    "envb_pos2",
                    models.TextField(blank=True, db_column="ENVB_Pos2", null=True),
                ),
                (
                    "envb_bereich",
                    models.TextField(blank=True, db_column="ENVB_Bereich", null=True),
                ),
                (
                    "envb_langtext",
                    models.TextField(blank=True, db_column="ENVB_Langtext", null=True),
                ),
                (
                    "envb_anmerkung",
                    models.TextField(blank=True, db_column="ENVB_Anmerkung", null=True),
                ),
                (
                    "envb_ok",
                    models.TextField(blank=True, db_column="ENVB_OK", null=True),
                ),
            ],
            options={
                "db_table": "EN_Videobeispielekode",
                "managed": False,
            },
        ),
    ]
