# Generated by Django 5.0.3 on 2024-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='damage_codes',
            fields=[
                ('damage_codes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('damage_kodierung', models.CharField(max_length=3)),
                ('damage_kurztext', models.CharField(max_length=32)),
                ('damage_beschreibung', models.CharField(max_length=250)),
            ],
        ),
    ]
